org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Версии под Minecraft 1.21.1 (для порта меняются эти строки + немного кода)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5
fabric_version=0.102.0+1.21.1
java_version=21

mod_version=0.1.0
maven_group=com.nazarbatrider
archives_base_name=frozenbees
